UI Failure
Currently error:/usr/bin/python
/Users/programmer/Documents/Meejay/WebUI.py
Traceback (most recent call last):
  File "/Users/programmer/Documents/Meejay/WebUI.py", line 13, in
<module>
    myapp.run(debug=True)
  File
"/Users/programmer/Library/Python/2.7/lib/python/site-packages/flask/app
.py", line 772, in run
    run_simple(host, port, self, **options)
  File
"/Users/programmer/Library/Python/2.7/lib/python/site-packages/werkzeug/
serving.py", line 677, in run_simple
    s.bind((hostname, port))
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/
socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use

suspected issue: link creator needs to referrence the UI from somehow
not sure how